console.log("hello from workerd");

console.log(Object.getOwnPropertyNames(globalThis));
console.log(Object.getOwnPropertySymbols(globalThis));
// addEventListener("fetch", (event) => {
//   event.respondWith(handle(event.request));
// });
// throw new Error("haha");

// console.log(globalThis.Object);
// console.log(globalThis.Function);
// console.log(globalThis.Array);
// console.log(globalThis.Number);
// console.log(globalThis.parseFloat);
// console.log(globalThis.parseInt);
// console.log(globalThis.Infinity);
// console.log(globalThis.NaN);
console.log(globalThis.undefined);
// console.log(globalThis.Boolean);
// console.log(globalThis.String);
// console.log(globalThis.Symbol);
// console.log(globalThis.Date);
// console.log(globalThis.Promise);
// console.log(globalThis.RegExp);
// console.log(globalThis.Error);
// console.log(globalThis.AggregateError);
// console.log(globalThis.EvalError);
// console.log(globalThis.RangeError);
// console.log(globalThis.ReferenceError);
// console.log(globalThis.SyntaxError);
// console.log(globalThis.TypeError);
// console.log(globalThis.URIError);
// console.log(globalThis.globalThis);
// console.log(globalThis.JSON);
// console.log(globalThis.Math);
// console.log(globalThis.Intl);
// console.log(globalThis.ArrayBuffer);
// console.log(globalThis.Uint8Array);
// console.log(globalThis.Int8Array);
// console.log(globalThis.Uint16Array);
// console.log(globalThis.Int16Array);
// console.log(globalThis.Uint32Array);
// console.log(globalThis.Int32Array);
// console.log(globalThis.Float32Array);
// console.log(globalThis.Float64Array);
// console.log(globalThis.Uint8ClampedArray);
// console.log(globalThis.BigUint64Array);
// console.log(globalThis.BigInt64Array);
// console.log(globalThis.DataView);
// console.log(globalThis.Map);
// console.log(globalThis.BigInt);
// console.log(globalThis.Set);
// console.log(globalThis.WeakMap);
// console.log(globalThis.WeakSet);
// console.log(globalThis.Proxy);
// console.log(globalThis.Reflect);
// console.log(globalThis.decodeURI);
// console.log(globalThis.decodeURIComponent);
// console.log(globalThis.encodeURI);
// console.log(globalThis.encodeURIComponent);
// console.log(globalThis.escape);
// console.log(globalThis.unescape);
// console.log(globalThis.eval);
// console.log(globalThis.isFinite);
// console.log(globalThis.isNaN);
console.log(Object.getOwnPropertyNames(globalThis.console));
console.log(Object.getOwnPropertyNames(globalThis.navigator));
// console.log(globalThis.origin); // it will throw
console.log(Object.getOwnPropertyNames(globalThis.scheduler));
// console.log(globalThis.caches);
// console.log(globalThis.crypto);
// console.log(globalThis.self);
// console.log(globalThis.SharedArrayBuffer);
// console.log(globalThis.Atomics);
// console.log(globalThis.WebAssembly);
// console.log(globalThis.ServiceWorkerGlobalScope);
console.log(Object.getOwnPropertyNames(Object.getPrototypeOf(globalThis)));
throw new Error("end");
